### ISSUE TITLE
[Suggestion] use appdirs

### ISSUE THREAD

**Issue by NikkyAI** [Victorious3/cutespamtk#1]
i do not quite know why or how you make the pip installed package modify files in the source, but this will most likely break once people install it from PyPi

why not use https://pypi.org/project/appdirs/ and write config in `~/.config/cutespam`
and caches in `~/.local/cache/cutespam`

**Comment by Victorious3** [comment]
https://github.com/Victorious3/cutespamtk/blob/8b3e0e3a99beef056f916821c8cf69f9e423308e/cutespam/config.py#L48-L55
